// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID        int32              `json:"id"`
	UserID    string             `json:"user_id"`
	DeviceID  string             `json:"device_id"`
	Platform  string             `json:"platform"`
	FcmToken  string             `json:"fcm_token"`
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TestRun struct {
	Nonce     string             `json:"nonce"`
	UserID    string             `json:"user_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AckedAt   pgtype.Timestamptz `json:"acked_at"`
}
