// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const countTables = `-- name: CountTables :one
SELECT COUNT(*) 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('devices', 'test_runs')
`

func (q *Queries) CountTables(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTables)
	var count int64
	err := row.Scan(&count)
	return count, err
}
