// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AckTestRun(ctx context.Context, nonce string) (TestRun, error)
	CreateTestRun(ctx context.Context, arg CreateTestRunParams) error
	DeactivateDevice(ctx context.Context, deviceID string) error
	GetDeviceByDeviceID(ctx context.Context, deviceID string) (GetDeviceByDeviceIDRow, error)
	GetTestRunByNonce(ctx context.Context, nonce string) (TestRun, error)
	ListActiveDevicesByPlatforms(ctx context.Context, userID string) ([]ListActiveDevicesByPlatformsRow, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
}

var _ Querier = (*Queries)(nil)
