// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (user_id, device_id, platform, fcm_token, is_active, updated_at)
VALUES ($1, $2, $3, $4, TRUE, NOW())
ON CONFLICT (user_id, device_id)
DO UPDATE SET
    fcm_token = EXCLUDED.fcm_token,
    is_active = TRUE,
    updated_at = NOW()
`

type UpsertDeviceParams struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Platform string `json:"platform"`
	FcmToken string `json:"fcm_token"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice,
		arg.UserID,
		arg.DeviceID,
		arg.Platform,
		arg.FcmToken,
	)
	return err
}
