package com.example.fcmplayground

import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.content.ContextCompat
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.fcmplayground.ui.theme.FcmplaygroundTheme
import com.google.firebase.messaging.FirebaseMessaging

class MainActivity : ComponentActivity() {
    companion object {
        const val TAG = "FCM"
        const val FCM_TOKEN_NOT_AVAILABLE = "FCM token not available yet"
        const val FCM_TOKEN_NOT_PREFIX = "FCM token not"
        const val DEBUG_USER_ID = "debug-user-1"
        
        // Log messages
        const val LOG_PERMISSION_GRANTED = "Notification permission granted"
        const val LOG_PERMISSION_DENIED = "Notification permission denied"
        const val LOG_PERMISSION_ALREADY_GRANTED = "Notification permission already granted"
        const val LOG_TOKEN_FETCH_FAILED = "Fetching FCM registration token failed"
        const val LOG_MANUAL_FETCH_TOKEN = "Manual fetch token: "
    }

    // Permission request launcher for Android 13+
    private val requestPermissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { isGranted: Boolean ->
        if (isGranted) {
            Log.d(TAG, LOG_PERMISSION_GRANTED)
        } else {
            Log.w(TAG, LOG_PERMISSION_DENIED)
        }
    }

    private fun requestNotificationPermission() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            when {
                ContextCompat.checkSelfPermission(
                    this,
                    Manifest.permission.POST_NOTIFICATIONS
                ) == PackageManager.PERMISSION_GRANTED -> {
                    Log.d(TAG, LOG_PERMISSION_ALREADY_GRANTED)
                }
                else -> {
                    requestPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
                }
            }
        }
    }
   
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        // Request notification permission for Android 13+
        requestNotificationPermission()

        // fixed debug user id
        val userId = DEBUG_USER_ID

        // persistent device id from SharedPreferences
        val deviceId = DeviceIdManager.getOrCreateDeviceId(this)

        // API base URL from BuildConfig (generated by build.gradle.kts)
        val apiBaseUrl = BuildConfig.API_BASE_URL

        val initialFcmToken = FcmTokenStore.getToken(this) ?: FCM_TOKEN_NOT_AVAILABLE


        FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
            if (!task.isSuccessful) {
                Log.w(TAG, LOG_TOKEN_FETCH_FAILED, task.exception)
                return@addOnCompleteListener
            }

            val token = task.result
            Log.d(TAG, "$LOG_MANUAL_FETCH_TOKEN$token")
            FcmTokenStore.saveToken(this, token)
        }

        if (!initialFcmToken.startsWith(FCM_TOKEN_NOT_PREFIX)) {
            DeviceRegister.registerDevice(
                context = this,
                userId = userId,
                deviceId = deviceId,
                fcmToken = initialFcmToken,
                apiBaseUrl = apiBaseUrl
            )
        }



        setContent {
            FcmplaygroundTheme {
                MainScreen(
                    userId = userId,
                    deviceId = deviceId,
                    apiBaseUrl = apiBaseUrl,
                    initialFcmToken = initialFcmToken,
                    onReRegisterClick = { latestFcmToken ->
                        DeviceRegister.registerDevice(
                            context = this,
                            userId = userId,
                            deviceId = deviceId,
                            fcmToken = latestFcmToken,
                            apiBaseUrl = apiBaseUrl
                        )
                    }
                )
            }
        }
    }

}

private object MainScreenConstants {
    // UI Strings
    const val LABEL_USER_ID = "user_id: "
    const val LABEL_DEVICE_ID = "device_id: "
    const val LABEL_FCM_TOKEN = "FCM token: "
    const val LABEL_API_BASE_URL = "API_BASE_URL: "
    const val BUTTON_RE_REGISTER = "Re-register device"
    
    // Dimensions
    val PADDING_SCREEN = 16.dp
    val SPACING_SMALL = 8.dp
    val SPACING_MEDIUM = 16.dp
    
    // Preview
    const val PREVIEW_DEVICE_ID = "preview-device-id"
    const val PREVIEW_API_BASE_URL = "https://example.com/dev"
    const val PREVIEW_FCM_TOKEN = "preview-fcm-token"
}

@Composable
fun MainScreen(
    userId: String,
    deviceId: String,
    apiBaseUrl: String,
    initialFcmToken: String,
    onReRegisterClick: (String) -> Unit,
) {
    var fcmToken by remember { mutableStateOf(initialFcmToken) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(MainScreenConstants.PADDING_SCREEN)
    ) {
        Text("${MainScreenConstants.LABEL_USER_ID}$userId", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(MainScreenConstants.SPACING_SMALL))

        Text("${MainScreenConstants.LABEL_DEVICE_ID}$deviceId", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(MainScreenConstants.SPACING_SMALL))

        Text("${MainScreenConstants.LABEL_FCM_TOKEN}$fcmToken", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(MainScreenConstants.SPACING_SMALL))

        Text("${MainScreenConstants.LABEL_API_BASE_URL}$apiBaseUrl", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(MainScreenConstants.SPACING_MEDIUM))

        Button(
            onClick = {
                onReRegisterClick(fcmToken)
            }
        ) {
            Text(MainScreenConstants.BUTTON_RE_REGISTER)
        }
    }
}


@Preview(showBackground = true)
@Composable
fun MainScreenPreview() {
    FcmplaygroundTheme {
        MainScreen(
            userId = MainActivity.DEBUG_USER_ID,
            deviceId = MainScreenConstants.PREVIEW_DEVICE_ID,
            apiBaseUrl = MainScreenConstants.PREVIEW_API_BASE_URL,
            initialFcmToken = MainScreenConstants.PREVIEW_FCM_TOKEN,
            onReRegisterClick = {}
        )
    }
}
