package com.example.fcmplayground

import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.fcmplayground.ui.theme.FcmplaygroundTheme
import com.google.firebase.messaging.FirebaseMessaging
import kotlinx.coroutines.*
import java.net.HttpURLConnection
import java.net.URL
import androidx.compose.runtime.rememberCoroutineScope
import kotlinx.coroutines.launch
import androidx.compose.material3.OutlinedTextField

class MainActivity : ComponentActivity() {
    companion object {
        private const val CONNECTION_TIMEOUT_MS = 10_000
        private const val READ_TIMEOUT_MS = 10_000
        private const val REGISTER_PATH = "/devices/register"
    }


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        // fixed debug user id
        val userId = "debug-user-1"

        // persistent device id from SharedPreferences
        val deviceId = DeviceIdManager.getOrCreateDeviceId(this)

        // API base URL from BuildConfig (generated by build.gradle.kts)
        val apiBaseUrl = BuildConfig.API_BASE_URL

        val initialFcmToken = FcmTokenStore.getToken(this) ?: "FCM token not available yet"


        FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
            if (!task.isSuccessful) {
                Log.w("FCM", "Fetching FCM registration token failed", task.exception)
                return@addOnCompleteListener
            }

            val token = task.result
            Log.d("FCM", "Manual fetch token: $token")
            FcmTokenStore.saveToken(this, token)
        }

        if (!initialFcmToken.startsWith("FCM token not")
        ) {
            DeviceRegister.registerDevice(
                context = this,
                userId = userId,
                deviceId = deviceId,
                fcmToken = initialFcmToken,
                apiBaseUrl = apiBaseUrl
            )
        }



        setContent {
            FcmplaygroundTheme {
                MainScreen(
                    userId = userId,
                    deviceId = deviceId,
                    apiBaseUrl = apiBaseUrl,
                    initialFcmToken = initialFcmToken,
                    onReRegisterClick = { latestFcmToken ->
                        DeviceRegister.registerDevice(
                            context = this,
                            userId = userId,
                            deviceId = deviceId,
                            fcmToken = latestFcmToken,
                            apiBaseUrl = apiBaseUrl
                        )
                    }
                )
            }
        }
    }

}

@Composable
fun MainScreen(
    userId: String,
    deviceId: String,
    apiBaseUrl: String,
    initialFcmToken: String,
    onReRegisterClick: (String) -> Unit,
) {

    var fcmToken by remember { mutableStateOf(initialFcmToken) }
    var nonceInput by remember { mutableStateOf("") }
    var statusText by remember { mutableStateOf("") }
    val scope = rememberCoroutineScope()



    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        Text("user_id: $userId", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(8.dp))

        Text("device_id: $deviceId", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(8.dp))

        Text("FCM token: $fcmToken", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(8.dp))

        Text("API_BASE_URL: $apiBaseUrl", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(16.dp))

        Button(
            onClick = {
                // send fcmToken to Activity
                onReRegisterClick(fcmToken)
            }
        ) {
            Text("Re-register device")
        }
        Spacer(Modifier.height(24.dp))

        OutlinedTextField(
            value = nonceInput,
            onValueChange = { nonceInput = it },
            label = { Text("nonce for /test/status") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(Modifier.height(8.dp))

        Button(
            onClick = {
                if (nonceInput.isNotBlank()) {
                    scope.launch {
                        statusText = "Checking status..."
                        statusText = checkTestStatus(apiBaseUrl, nonceInput)
                    }
                } else {
                    statusText = "Please enter a nonce"
                }
            }
        ) {
            Text("Check test status")
        }

        Spacer(Modifier.height(12.dp))

        if (statusText.isNotEmpty()) {
            Text("Status: $statusText", style = MaterialTheme.typography.bodyMedium)
        }


    }
}


@Preview(showBackground = true)
@Composable
fun MainScreenPreview() {
    FcmplaygroundTheme {
        MainScreen(
            userId = "debug-user-1",
            deviceId = "preview-device-id",
            apiBaseUrl = "https://example.com/dev",
            initialFcmToken = "preview-fcm-token",
            onReRegisterClick = {}
        )
    }
}

suspend fun checkTestStatus(apiBaseUrl: String, nonce: String): String =
    withContext(Dispatchers.IO) {
        try {
            val url = URL("$apiBaseUrl/test/status?nonce=$nonce")
            val conn = (url.openConnection() as HttpURLConnection).apply {
                requestMethod = "GET"
                connectTimeout = CONNECTION_TIMEOUT_MS
                readTimeout = READ_TIMEOUT_MS
            }

            val code = conn.responseCode
            val responseText = try {
                conn.inputStream.bufferedReader().use { it.readText() }
            } catch (_: Exception) {
                ""
            } finally {
                conn.disconnect()
            }

            Log.d("API", "test/status HTTP $code, response=$responseText")

            return@withContext when {
                code in 200..299 && responseText.isNotBlank() -> responseText
                code in 200..299 -> "OK"
                else -> "HTTP $code"
            }
        } catch (e: Exception) {
            Log.e("API", "test/status failed", e)
            return@withContext "Error: ${e.message}"
        }
    }
