package com.example.fcmplayground

import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.fcmplayground.ui.theme.FcmplaygroundTheme
import com.google.firebase.messaging.FirebaseMessaging
import kotlinx.coroutines.*
import java.net.HttpURLConnection
import java.net.URL

class MainActivity : ComponentActivity() {
    companion object {
        const val CONNECTION_TIMEOUT_MS = 10_000
        const val READ_TIMEOUT_MS = 10_000
        const val REGISTER_PATH = "/devices/register"
        const val TAG = "FCM"
        const val FCM_TOKEN_NOT_AVAILABLE = "FCM token not available yet"
        const val FCM_TOKEN_NOT_PREFIX = "FCM token not"
        
        // Debug/Test
        const val DEBUG_USER_ID = "debug-user-1"
        
        // HTTP
        const val HTTP_METHOD_GET = "GET"
        const val HTTP_SUCCESS_CODE_MIN = 200
        const val HTTP_SUCCESS_CODE_MAX = 299
        const val HTTP_RESPONSE_OK = "OK"
        
        // Log tags
        const val LOG_TAG_API = "API"
        
        // URL query parameters
        const val QUERY_PARAM_NONCE = "nonce"
        
        // Status messages
        const val STATUS_CHECKING = "Checking status..."
        const val ERROR_NO_NONCE = "Please enter a nonce"
    }
   
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        // fixed debug user id
        val userId = DEBUG_USER_ID

        // persistent device id from SharedPreferences
        val deviceId = DeviceIdManager.getOrCreateDeviceId(this)

        // API base URL from BuildConfig (generated by build.gradle.kts)
        val apiBaseUrl = BuildConfig.API_BASE_URL

        val initialFcmToken = FcmTokenStore.getToken(this) ?: FCM_TOKEN_NOT_AVAILABLE


        FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
            if (!task.isSuccessful) {
                Log.w(TAG, "Fetching FCM registration token failed", task.exception)
                return@addOnCompleteListener
            }

            val token = task.result
            Log.d(TAG, "Manual fetch token: $token")
            FcmTokenStore.saveToken(this, token)
        }

        if (!initialFcmToken.startsWith(FCM_TOKEN_NOT_PREFIX)) {
            DeviceRegister.registerDevice(
                context = this,
                userId = userId,
                deviceId = deviceId,
                fcmToken = initialFcmToken,
                apiBaseUrl = apiBaseUrl
            )
        }



        setContent {
            FcmplaygroundTheme {
                MainScreen(
                    userId = userId,
                    deviceId = deviceId,
                    apiBaseUrl = apiBaseUrl,
                    initialFcmToken = initialFcmToken,
                    onReRegisterClick = { latestFcmToken ->
                        DeviceRegister.registerDevice(
                            context = this,
                            userId = userId,
                            deviceId = deviceId,
                            fcmToken = latestFcmToken,
                            apiBaseUrl = apiBaseUrl
                        )
                    }
                )
            }
        }
    }

}

@Composable
fun MainScreen(
    userId: String,
    deviceId: String,
    apiBaseUrl: String,
    initialFcmToken: String,
    onReRegisterClick: (String) -> Unit,
) {

    var fcmToken by remember { mutableStateOf(initialFcmToken) }
    var nonceInput by remember { mutableStateOf("") }
    var statusText by remember { mutableStateOf("") }
    val scope = rememberCoroutineScope()



    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        Text("user_id: $userId", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(8.dp))

        Text("device_id: $deviceId", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(8.dp))

        Text("FCM token: $fcmToken", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(8.dp))

        Text("API_BASE_URL: $apiBaseUrl", style = MaterialTheme.typography.bodyLarge)
        Spacer(Modifier.height(16.dp))

        Button(
            onClick = {
                // send fcmToken to Activity
                onReRegisterClick(fcmToken)
            }
        ) {
            Text("Re-register device")
        }
        Spacer(Modifier.height(24.dp))

        OutlinedTextField(
            value = nonceInput,
            onValueChange = { nonceInput = it },
            label = { Text("nonce for /test/status") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(Modifier.height(8.dp))

        Button(
            onClick = {
                if (nonceInput.isNotBlank()) {
                    scope.launch {
                        statusText = MainActivity.STATUS_CHECKING
                        statusText = checkTestStatus(apiBaseUrl, nonceInput)
                    }
                } else {
                    statusText = MainActivity.ERROR_NO_NONCE
                }
            }
        ) {
            Text("Check test status")
        }

        Spacer(Modifier.height(12.dp))

        if (statusText.isNotEmpty()) {
            Text("Status: $statusText", style = MaterialTheme.typography.bodyMedium)
        }


    }
}


@Preview(showBackground = true)
@Composable
fun MainScreenPreview() {
    FcmplaygroundTheme {
        MainScreen(
            userId = MainActivity.DEBUG_USER_ID,
            deviceId = "preview-device-id",
            apiBaseUrl = "https://example.com/dev",
            initialFcmToken = "preview-fcm-token",
            onReRegisterClick = {}
        )
    }
}

suspend fun checkTestStatus(apiBaseUrl: String, nonce: String): String =
    withContext(Dispatchers.IO) {
        try {
            val url = URL("$apiBaseUrl${ApiRoutes.TEST_STATUS}?${MainActivity.QUERY_PARAM_NONCE}=$nonce")
            val conn = (url.openConnection() as HttpURLConnection).apply {
                requestMethod = MainActivity.HTTP_METHOD_GET
                connectTimeout = MainActivity.CONNECTION_TIMEOUT_MS
                readTimeout = MainActivity.READ_TIMEOUT_MS
            }

            val code = conn.responseCode
            val responseText = try {
                conn.inputStream.bufferedReader().use { it.readText() }
            } catch (_: Exception) {
                ""
            } finally {
                conn.disconnect()
            }

            Log.d(MainActivity.LOG_TAG_API, "${ApiRoutes.TEST_STATUS} HTTP $code, response=$responseText")

            return@withContext when {
                code in MainActivity.HTTP_SUCCESS_CODE_MIN..MainActivity.HTTP_SUCCESS_CODE_MAX && responseText.isNotBlank() -> responseText
                code in MainActivity.HTTP_SUCCESS_CODE_MIN..MainActivity.HTTP_SUCCESS_CODE_MAX -> MainActivity.HTTP_RESPONSE_OK
                else -> "HTTP $code"
            }
        } catch (e: Exception) {
            Log.e(MainActivity.LOG_TAG_API, "${ApiRoutes.TEST_STATUS} failed", e)
            return@withContext "Error: ${e.message}"
        }
    }
